# Generated by Django 3.1.6 on 2021-02-14 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='votes_to_skipe',
            new_name='vote_to_skip',
        ),
    ]
